### ISSUE TITLE
Importing in python 3.6 Raises ModuleNotFoundError

### ISSUE THREAD

**Issue by jamesbiederbeck** [AuguriaTeam/python-akeneo#1]
Attempting to execute `from akeneo import AkeneoAPI` raises `ModuleNotFoundError: No module named 'version'
`
Any idea how to resolve?

Here is the full traceback:
```
C:\Users\james\development\project2\cheddar>python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from akeneo import AkeneoAPI
  File "C:\Users\james\development\Project\lib\site-packages\akeneo\__init__.py", line 12, in <module>
    from .api import AkeneoAPI
  File "C:\Users\james\development\Project\lib\site-packages\akeneo\api.py", line 22, in <module>
    from version import __version__
ModuleNotFoundError: No module named 'version'

```

**Comment by thomasfaure3** [comment]
Hi, same for me, @jamesbiederbeck if you found the solution i will be pleased to know it :)
